name: GitHub Actions PhpScan
on:
  push:
    branches:
      - master
      - main
jobs:
  Phpscan-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Phpscan Vulnerabilities Scanner
        uses: phpscan/phpscan_action@v0.1.7
        env:
          PROJECT_NAME: "CI/CD Real Test"
          PHPSCAN_AUTH_TOKEN: ${{ secrets.PHPSCAN_AUTH_TOKEN }}